"""weapon_spells and role_spells_color

Revision ID: 0de970cc65bd
Revises: 
Create Date: 2026-06-21 19:11:50.898334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0de970cc65bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon_spells',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weapon_base_id', sa.String(length=128), nullable=False),
    sa.Column('slot', sa.String(length=8), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uisprite', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_spells_weapon_base_id'), 'weapon_spells', ['weapon_base_id'], unique=False)
    op.add_column('game_roles', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('game_roles', sa.Column('q_spell', sa.String(length=128), nullable=True))
    op.add_column('game_roles', sa.Column('w_spell', sa.String(length=128), nullable=True))
    op.add_column('game_roles', sa.Column('passive_spell', sa.String(length=128), nullable=True))
    # guild_members.discord_role_ids: TEXT em SQLite, sem mudança necessária
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('game_roles', 'passive_spell')
    op.drop_column('game_roles', 'w_spell')
    op.drop_column('game_roles', 'q_spell')
    op.drop_column('game_roles', 'color')
    op.drop_index(op.f('ix_weapon_spells_weapon_base_id'), table_name='weapon_spells')
    op.drop_table('weapon_spells')
    # ### end Alembic commands ###
