import { useCallback, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { getVersion } from "@tauri-apps/api/app";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useLang, useT, LANG_FULL, type Lang, type LangPref } from "./i18n";

type CompanionConfig = { api_base_url: string; collect_damage_meter: boolean; collect_auto_lootlog: boolean; autostart: boolean; minimize_to_tray: boolean; spell_index_offset: number };
type SniffStats = { running: boolean; online: boolean; packets_captured: number; loot_count: number; damage_total: number; player_name: string; party_members: string[]; last_map_name: string; error: string | null };
type LootRow = { ts: string | null; item_id: string; item_name: string; item_name_pt: string; item_name_es: string; quantity: number; looted_by: string; looted_from: string };
type SkillRow = { id: number; name: string | null; name_pt: string | null; name_es: string | null; unique_name: string | null; icon: string | null; hits: number; total: number; avg: number; max_hit: number; pct: number };
type DamageRow = { name: string; weapon: string | null; damage: number; dps: number; skills: SkillRow[]; timeline: number[] };
type DebugLine = { ts: string; level: string; msg: string };

function usePoll(fn: () => void | Promise<void>, ms: number, deps: unknown[] = []) {
  const latest = useRef(fn); latest.current = fn;
  useEffect(() => { let alive = true; const tick = () => { if (alive) void latest.current(); }; tick(); const id = setInterval(tick, ms); return () => { alive = false; clearInterval(id); }; }, [ms, ...deps]);
}
function fmt(n: number) { return Math.round(n).toLocaleString("pt-BR"); }
function itemName(row: LootRow, lang: Lang) { return lang === "pt" ? row.item_name_pt : lang === "es" ? row.item_name_es : row.item_name; }
function time(ts: string | null) { return ts?.slice(11, 16) ?? ""; }

export default function App() {
  const t = useT(); const { pref, setPref } = useLang();
  const [config, setConfig] = useState<CompanionConfig | null>(null);
  const [stats, setStats] = useState<SniffStats | null>(null);
  const [tab, setTab] = useState<"damage" | "loot">("damage");
  const [version, setVersion] = useState("");
  const [settings, setSettings] = useState(false);
  const [updateAvailable, setUpdateAvailable] = useState(false);
  const [updating, setUpdating] = useState(false);
  const refresh = useCallback(async () => setConfig(await invoke<CompanionConfig>("get_config")), []);
  useEffect(() => { void refresh(); getVersion().then(setVersion).catch(() => {}); }, [refresh]);
  useEffect(() => { let unlisten: (() => void) | undefined; void listen<string>("update-status", event => { setUpdateAvailable(event.payload === "available"); setUpdating(event.payload === "downloading"); }).then(stop => { unlisten = stop; }); return () => unlisten?.(); }, []);
  const applyUpdate = async () => { if (updating) return; setUpdating(true); try { await invoke("check_and_apply_update"); } catch { setUpdating(false); } };
  usePoll(async () => { try { setStats(await invoke<SniffStats>("get_sniff_stats")); } catch {} }, 2000);
  const update = async (key: keyof CompanionConfig, value: unknown) => { await invoke("set_config", { key, value }); await refresh(); };
  if (!config) return <div className="splash"><img className="splash-logo" src="/logo.png" alt="Ziggs" /><div className="splash-text">{t("splashText")}</div></div>;
  return <div className="ck-root"><header className="ck-bar" onMouseDown={e => { if (e.button === 0 && !(e.target as HTMLElement).closest("button")) getCurrentWindow().startDragging(); }}><img className="logo" src="/logo.png" alt="Ziggs" /><span className="ck-brand">ZIGGS</span><span className="ck-version">v{version}</span><span className="ck-sep" /><span className="ck-chip"><span className="ck-lbl">{t("ckPackets")}</span><b className="ck-num">{fmt(stats?.packets_captured ?? 0)}</b></span><span className="ck-winbtns"><button className="ck-winbtn" onClick={() => getCurrentWindow().minimize()}>—</button><button className="ck-winbtn" onClick={() => getCurrentWindow().close()}>×</button></span></header><div className="ck-shell"><aside className="ck-side"><button className={`ck-side-tab ${tab === "damage" ? "selected" : ""}`} onClick={() => setTab("damage")}><span>{t("navDamage")}</span><b className="ck-ok">{fmt(stats?.damage_total ?? 0)}</b><Toggle on={config.collect_damage_meter} onChange={v => void update("collect_damage_meter", v)} /></button><button className={`ck-side-tab ${tab === "loot" ? "selected" : ""}`} onClick={() => setTab("loot")}><span>Lootlog</span><b className="ck-ok">{stats?.loot_count ?? 0}</b><Toggle on={config.collect_auto_lootlog} onChange={v => void update("collect_auto_lootlog", v)} /></button><div className="ck-side-foot"><b>{stats?.online ? stats.last_map_name || t("statusLoading") : t("albionClosed")}</b>{updateAvailable && <button className="ck-side-update" onClick={() => void applyUpdate()} disabled={updating} aria-live="polite">{updating ? "Baixando atualização..." : "Atualizar"}</button>}<button className="ck-side-gear" onClick={() => setSettings(true)}>{t("navConfig")}</button></div></aside><main className="ck-main"><div className="ck-full">{tab === "damage" ? <Damage config={config} stats={stats} /> : <Loot config={config} />}</div></main></div>{settings && <Settings config={config} pref={pref} setPref={setPref} update={update} close={() => setSettings(false)} />}</div>;
}
function Toggle({ on, onChange }: { on: boolean; onChange: (value: boolean) => void }) { return <span className={`toggle ${on ? "on" : ""}`} role="switch" aria-checked={on} onClick={e => { e.stopPropagation(); onChange(!on); }}><span /></span>; }
function Damage({ config, stats }: { config: CompanionConfig; stats: SniffStats | null }) { const t = useT(); const { lang } = useLang(); const [rows, setRows] = useState<DamageRow[]>([]); const [vsPlayers, setVsPlayers] = useState(false); usePoll(async () => { if (config.collect_damage_meter) setRows(await invoke<DamageRow[]>("get_damage_meter", { vsPlayers })); }, 2000, [config.collect_damage_meter, vsPlayers]); if (!config.collect_damage_meter) return <div className="ck-panel ck-dmg"><h2>{t("navDamage")}</h2><div className="empty-area">{t("dmgOffHint")}</div></div>; return <div className="ck-panel ck-dmg"><div className="card-head"><h2>{t("navDamage")}</h2><button className={`dmg-chip ${vsPlayers ? "active" : ""}`} onClick={() => setVsPlayers(!vsPlayers)}>{t("dmgVsPlayers")}</button><button className="btn small" onClick={() => void invoke("clear_damage_meter").then(() => setRows([]))}>{t("clearLoot")}</button></div>{rows.length === 0 ? <div className="empty-area">{t("dmgEmptyHint")}</div> : <div className="dmg-list">{rows.map((row, i) => <div className="dmg-entry" key={row.name}><div className="dmg-row"><span className="dmg-rank">{i + 1}</span><span className="dmg-name">{row.name}</span><span className="dmg-val">{fmt(row.damage)}</span><span className="dmg-dps">{fmt(row.dps)}/s</span></div><div className="dmg-skills">{row.skills.map(skill => <div className="dmg-skill-row" key={skill.id}><span>{lang === "pt" ? skill.name_pt ?? skill.name : lang === "es" ? skill.name_es ?? skill.name : skill.name ?? t("dmgSkillN", { id: skill.id })}</span><span>{skill.hits}×</span><span>{fmt(skill.total)}</span></div>)}</div></div>)}</div>}<small>{stats?.player_name}</small></div>; }
function Loot({ config }: { config: CompanionConfig }) { const t = useT(); const { lang } = useLang(); const [rows, setRows] = useState<LootRow[]>([]); const [debug, setDebug] = useState<DebugLine[]>([]); usePoll(async () => { const [loot, lines] = await Promise.all([invoke<LootRow[]>("get_captured_loot"), invoke<DebugLine[]>("get_sniffer_debug")]); setRows(loot); setDebug(lines); }, 2000); if (!config.collect_auto_lootlog) return <div className="ck-panel ck-loot"><h2>Lootlog</h2><div className="empty-area">{t("lootlogOffHint")}</div></div>; return <div className="ck-panel ck-loot"><div className="card-head"><h2>{t("capturedLoot")}</h2><button className="btn" disabled={!rows.length} onClick={() => void invoke("save_lootlog_csv")}>{t("downloadCsv")}</button><button className="btn" disabled={!rows.length} onClick={() => void invoke("clear_captured_loot").then(() => setRows([]))}>{t("clearLoot")}</button></div><div className="terminal">{debug.filter(line => line.level !== "info").map((line, i) => <div className="terminal-line" key={`d${i}`}>[{line.level}] {line.msg}</div>)}{rows.map((row, i) => <div className="terminal-line" key={`l${i}`}><span className="t-time">{time(row.ts)}</span> <span className="t-loot-tag">[LOOT]</span> {row.looted_by} {t("lootedBy")} {row.quantity > 1 ? `${row.quantity}× ` : ""}{itemName(row, lang)} {t("from")} {row.looted_from}</div>)}</div></div>; }
function Settings({ config, pref, setPref, update, close }: { config: CompanionConfig; pref: LangPref; setPref: (value: LangPref) => void; update: (key: keyof CompanionConfig, value: unknown) => Promise<void>; close: () => void }) { const t = useT(); return <div className="ck-modal-backdrop" onClick={close}><div className="ck-modal" onClick={e => e.stopPropagation()}><div className="ck-modal-head"><h2>{t("navConfig")}</h2><button onClick={close}>×</button></div><div className="ck-modal-body"><label>{t("language")}<select value={pref} onChange={e => setPref(e.target.value as LangPref)}><option value="auto">{t("langAuto")}</option>{Object.entries(LANG_FULL).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>{t("autostart")}<Toggle on={config.autostart} onChange={v => void update("autostart", v)} /></label><label>{t("minimizeTray")}<Toggle on={config.minimize_to_tray} onChange={v => void update("minimize_to_tray", v)} /></label></div></div></div>; }
